language: node_js
node_js:
- 6.9.1
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn run test:coverage
- yarn run build
deploy:
  provider: npm
  skip_cleanup: true
  email: ##
  api_key:
    secure: ##
  on:
    repo: ygnr/npm-module-es6-boilerplate
    branch: master
